version: '2.4'

services:
  postgre:
    image: postgres
#    volumes:
#      - ./db-data/data:/var/lib/postgresql/data
#      - ./db-data/log:/var/log/postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    ports:
      - 5432:5432
  flyway:
    image: flyway/flyway
#    command: info
    command: -url=jdbc:postgresql://postgre/dbname -schemas=xshema -user=user -password=pass -connectRetries=60 -validateOnMigrate=false migrate
    volumes:
      - ./postgres:/flyway/sql
    depends_on:
      - postgre